version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: orders-mysql
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Priyesh@123
      MYSQL_DATABASE: order_service
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  orderservice:
    build: .
    container_name: orders-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_service
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass
    ports:
      - "8081:8080"

volumes:
  mysql_data: